import type { LegalDocument } from '../content/legal';

/** Translation of the local source including the HubSpot provider update; not a legal review. */
export const englishLegal: Record<string, Pick<LegalDocument, 'title' | 'description' | 'intro' | 'metaItems' | 'sections'>> = {
  datenschutz: {
    title: 'Privacy policy',
    description: 'Privacy policy covering processed data, legal bases, data subject rights and contact details.',
    metaItems: [{ label: 'Effective from', value: '16-April-2026' }, { label: 'Updated on', value: '16-September-2026' }],
    intro: '<p>This privacy policy explains the policies of https://consultry.de regarding the collection, use, disclosure and protection of personal data collected when you access https://consultry.de (the “Service”). It defines and describes your privacy rights and the protection you enjoy under applicable data protection laws.</p><p>By using our Service, you agree to the collection and use of your personal data in accordance with this privacy policy. Please do not access or use our Service if you do not agree to the collection and use of your information as described here. This privacy policy was created with the help of the CookieScript Privacy Policy Generator.</p>',
    sections: [
      { title: 'What information we collect, for what purposes and on what legal basis', html: `<p>The legal bases below are defined as follows:</p>
<p><strong>Legitimate interests:</strong> The interests of the company or a third party, provided your interests or fundamental rights and freedoms do not override them and use of your personal data is proportionate to your rights and freedoms.</p>
<p><strong>Performance of a contract:</strong> Processing personal data where necessary to perform a contract to which you are a party or to take steps prior to entering into a contract.</p>
<p><strong>Legal obligations:</strong> Processing personal data where necessary to comply with a legal or regulatory obligation to which we are subject.</p>
<p><strong>Consent:</strong> Any freely given, specific, informed and unambiguous indication of your wishes by which, through a statement or clear affirmative action, you agree to the processing of personal data relating to you. We may request consent where we have no other legal basis for processing your data.</p>
<p><strong>Usage data</strong><br/>What we collect: Information about how users interact with our website or application, including pages visited, time spent on pages, click paths and browser details.<br/>Purpose: Analysing user behaviour, optimising performance and improving the user experience.<br/>Retention period: 365 days<br/>Legal basis: Legitimate interests</p>
<p><strong>Personal identification information</strong><br/>What we collect: Email address, mobile phone number<br/>Purpose: Managing user accounts, ensuring secure access and providing personalised content.<br/>Retention period: 730 days<br/>Legal basis: Consent</p>
<p><strong>Contact information</strong><br/>What we collect: Work phone number, work email<br/>Purpose: Ensuring correct service delivery and supporting account-related communications.<br/>Retention period: 730 days<br/>Legal basis: Consent</p>
<p><strong>Online identifiers &amp; device information</strong><br/>What we collect: IP address, browser type and version, operating system<br/>Purpose: Securing our platform, optimising performance and understanding technical usage.<br/>Retention period: 365 days<br/>Legal basis: Consent</p>
<p><strong>Location data</strong><br/>What we collect: Geolocation (GPS coordinates, location based on IP address)<br/>Purpose: Personalising experiences and services based on your location.<br/>Retention period: 365 days<br/>Legal basis: Consent</p>
<p><strong>Communication data</strong><br/>What we collect: Email correspondence<br/>Purpose: Providing customer support and maintaining a correspondence history.<br/>Retention period: 730 days<br/>Legal basis: Legitimate interests</p>
<p><strong>Preference and behavioural data</strong><br/>What we collect: User interests and preferences, history of interactions with content or products<br/>Purpose: Personalising recommendations, advertising and content.<br/>Retention period: 730 days<br/>Legal basis: Consent</p>
<p><strong>Professional information</strong><br/>What we collect: Company name, work email address, team size, industry, industry focus<br/>Purpose: Supporting business relationships and tailoring content for professional users.<br/>Retention period: 730 days<br/>Legal basis: Consent</p>
<p><strong>Consent and legal documents</strong><br/>What we collect: Consent forms<br/>Purpose: Meeting legal and regulatory obligations.<br/>Retention period: 730 days<br/>Legal basis: Consent</p>` },
      { title: 'How we obtain your personal data', html: '<p>We collect information that you provide directly when you:</p><ul><li>Complete forms</li><li>Use our services</li><li>Correspond with us</li><li>Contact us for other reasons</li></ul><p>Through cookies, consent tools, and analytics technologies on our website, where required only with your consent.</p><p>We may also obtain personal data from other legitimate sources:</p><ul><li>We may receive personal data from partners and collaborating companies</li></ul>' },
      { title: 'Requirement to provide personal data', html: '<p>In certain cases, providing personal data is required by law or contract, or is necessary to perform a contract.</p>' },
      { title: 'How we share your information', html: '<p>H&amp;W Digital Solutions UG may disclose your personal data to the following categories of recipients:</p><p>With your consent. H&amp;W Digital Solutions UG will share your data for any purpose with your express permission.</p><p>In business transfers. Your data will be transferred to third parties in the event of a merger, acquisition, negotiation, sale of business interests or financing.</p><p>We transfer personal data to the following third country: United States. This country, territory or the specified sectors have been recognised by the European Commission as providing an adequate level of data protection.</p>' },
      { title: 'Specific service providers and systems used', html: '<p>We currently use <strong>Vercel</strong> in particular for the technical provision and hosting of our Service.</p><p>For consent management and control, we use <strong>CookieScript</strong>, a service of <strong>Objectis Ltd.</strong>, Laisves st. 60, LT-05120 Vilnius, Lithuania.</p><p>For optional statistics and reach measurement, we use <strong>Google Tag Manager</strong> and <strong>Google Analytics 4</strong> after receiving your consent.</p><p>For waitlist registrations and email communications with your consent, we use <strong>HubSpot</strong> (HubSpot, Inc. and affiliated companies). On signup, we submit your email address, signup page, language, campaign information where provided, and the time and version of your consent. This form integration loads no HubSpot tracking code and sends neither tracking cookies nor the visitor IP address as a form field. Processing in the United States may occur. Further information is available in the <a href="https://legal.hubspot.com/privacy-policy" rel="noreferrer" target="_blank">HubSpot privacy policy</a>. Information on data processing and transfer mechanisms is available in the <a href="https://legal.hubspot.com/dpa" rel="noreferrer" target="_blank">HubSpot Data Processing Agreement</a>.</p><p>Where these services transfer personal data to third countries, particularly the United States, this takes place under the data protection and transfer mechanisms provided by the respective vendors.</p>' },
      { title: 'Data subject rights', html: `<p>You have the following rights regarding your personal data:</p><ul>
<li>Right of access: You may request a copy of the personal data we hold about you.</li>
<li>Right to rectification: You may request correction of inaccurate or incomplete information.</li>
<li>Right to erasure (right to be forgotten): Under certain conditions, you may request deletion of your personal data.</li>
<li>Right to restriction of processing: In certain circumstances, you may request restriction of processing of your personal data.</li>
<li>Right to data portability: You have the right to receive your personal data in a structured, commonly used and machine-readable format and to transmit that data to another controller.</li>
<li>Right to object: In certain cases, you may object to processing of your personal data.</li>
<li>Right to transparent information: You have the right to clear, transparent and readily understandable information about how we process your personal data.</li></ul>
<p><strong>Withdrawal of consent:</strong><br/>Under Article 13(2)(c) of the GDPR, you may withdraw your consent to processing of your personal data at any time. As a visitor to this website, you can adjust or withdraw consent directly through the consent banner provided on the website. Alternatively, contact the website operator using the contact details in this privacy policy. Withdrawal does not affect the lawfulness of processing carried out before the withdrawal.</p>
<p>To exercise these rights, contact us at <a href="mailto:contact@hw-digitalsolutions.de">contact@hw-digitalsolutions.de</a>.</p>
<p>We will act on your rights only after receiving your written request to exercise a specific right and verifying your identity.</p>
<p>Your request will be fulfilled, or a refusal with reasons will be provided, within one month of receipt of a request that complies with our internal rules and the GDPR. This period may be extended by two further months where a request is particularly complex due to the volume of personal data or other requests being processed at the same time. We will inform you of the extension and its reasons within one month of receiving the request. The response will be provided in your preferred form.</p>
<p>We may refuse a request where exceptions or restrictions on data subject rights under the GDPR apply, or where the request is manifestly unfounded or disproportionate. In the event of refusal, we will provide written reasons.</p>` },
      { title: 'Right to complain to a supervisory authority', html: '<p>You have the right to complain to a competent supervisory authority if you believe the processing of your personal data violates applicable law and your rights and legitimate interests. You may follow the procedures established for the Federal Commissioner for Data Protection and Freedom of Information (BfDI) of the Federal Republic of Germany, available at: <a href="https://www.bfdi.bund.de/anschriften" rel="noreferrer" target="_blank">https://www.bfdi.bund.de/anschriften</a>.</p><p>Please note that, despite all efforts, no system is completely secure. We have nevertheless implemented appropriate safeguards to minimise the risk of unauthorised access to or misuse of your personal data.</p>' },
      { title: 'Security', html: '<p>We and our third-party providers that may process personal data for the purposes described above are contractually required to keep it confidential.</p><p>We use appropriate security practices and procedures to protect the confidentiality and security of your information, including all non-public personal data.</p><p>We protect your data with appropriate physical, technical and administrative safeguards, including limiting access to employees who need to know the information.</p>' },
      { title: 'Changes to this policy', html: '<p>We review this privacy policy regularly and reserve the right to amend it at any time in accordance with applicable laws and regulations. Changes take effect immediately on publication on our website.</p><p>Please review this policy from time to time to stay informed of changes.</p>' },
      { title: 'Contact', html: '<p>For questions, please contact us using the following details:</p><p>Name: H&amp;W Digital Solutions UG<br/>Address: Greifswalder Straße 13D, 10405 Berlin<br/>Email: <a href="mailto:contact@hw-digitalsolutions.de">contact@hw-digitalsolutions.de</a><br/>Website: <a href="https://consultry.de">https://consultry.de</a><br/>Phone: +4917670937993</p>' },
    ],
  },
  impressum: {
    title: 'Legal notice', description: 'Provider information, contact details, commercial register entries and dispute resolution information.', intro: '', metaItems: [],
    sections: [
      { title: '1. Information under Section 5 DDG', html: '<p>The operator of this website and provider of <strong>Consultry</strong> is:</p><p><strong>H&amp;W Digital Solutions UG</strong><br/>Greifswalder Straße 13d<br/>10405 Berlin<br/>Germany</p>' },
      { title: '2. Registration and representation', html: '<p><strong>Commercial register:</strong> HRB 258903 B<br/><strong>Register court:</strong> Amtsgericht Charlottenburg (Berlin)</p><p><strong>Represented by:</strong></p><ul><li>Paul Hannemann</li><li>Julian Weber</li></ul>' },
      { title: '3. Contact', html: '<p><strong>Phone:</strong> +49 (0) 176 70937993<br/><strong>Email:</strong> <a href="mailto:contact@hw-digitalsolutions.de">contact@hw-digitalsolutions.de</a><br/><strong>Product enquiries:</strong> <a href="mailto:kontakt@consultry.com">kontakt@consultry.com</a></p>' },
      { title: '4. VAT identification number', html: '<p>VAT identification number under Section 27a of the German VAT Act:<br/><strong>DE365222097</strong></p>' },
      { title: '5. EU online dispute resolution', html: '<p>The European Commission provides a platform for online dispute resolution (ODR):<br/><a href="https://ec.europa.eu/consumers/odr/" rel="noreferrer" target="_blank">https://ec.europa.eu/consumers/odr/</a></p><p>Our email address is listed above in this legal notice.</p>' },
      { title: '6. Consumer dispute resolution', html: '<p>We are neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board.</p>' },
    ],
  },
  agb: {
    title: 'Terms and conditions', description: 'Provisional terms structure for pilot offers, product previews and future platform terms.', intro: '', metaItems: [],
    sections: [
      { title: '1. Provisional status', html: '<p>This page sets out the structure of the terms and conditions for the Consultry marketing website and product-related pilot offers.</p>' },
      { title: '2. Terms before launch', html: '<p>Until the final terms are published, pilot projects, workshops and product previews are governed by the individually agreed proposals and project agreements.</p>' },
      { title: '3. Areas covered by the final terms', html: '<p>The published terms will specifically govern scope of services, usage rights, liability, support conditions and contractual requirements for the Consultry platform.</p>' },
    ],
  },
};
