defaultPortal: jw-dev-1
portals:
  - name: jw-dev-1
    env: prod
    authType: personalaccesskey
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTEtMTdhNS01ZDY3LTRjNjYtYmZhNS03MzQ1NDlmN2ZmNDIQ3_e2FxiBiNEkKhkABeaRgozYt-0hR1GHn_sl7_TO-EjRfn9tSgNuYTE
    auth:
      tokenInfo:
        accessToken: >-
          CNbV6anUMxIgQlNQMl8kQEwrAhMACAkCFBwBAgEQAwoBAgMHGygCeAEY3_e2FyCBiNEkKO7pDDIU_HHpeF6tuh6Qhej32TaE3SANRlY6S0JTUDJfJEBMKwMnAAKDAgTLAgYTGR-QAbsBjgKPApUClwKrAq8CxwLUAtUC2gLbAu0C9gL5AvoCqwOsA4MEmgSbBN0EsQeyB7DxBUIUKfvI3N2dWK2Nq-MxpZf7Sri_CLFKA25hMVIAWgBgAWiBiNEkcAB4AA
        expiresAt: '2026-03-31T18:49:09.622Z'
    portalId: 49134559
