"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _homepage_hero_showcase_row from './homepage-hero-showcase-row.bones.json'
import _homepage_feature_showcase_stage from './homepage-feature-showcase-stage.bones.json'

registerBones({
  "homepage-hero-showcase-row": _homepage_hero_showcase_row,
  "homepage-feature-showcase-stage": _homepage_feature_showcase_stage,
})
